spring.application.name=modis

#MongogoDB Configuration
spring.mongodb.uri=mongodb+srv://dev_user:modis123@modis.hazw95q.mongodb.net/?appName=Modis
spring.mongodb.port=27017
spring.mongodb.database=Modis

#Redis
spring.data.redis.host=redis-16990.c52.us-east-1-4.ec2.cloud.redislabs.com
spring.data.redis.port=16990
spring.data.redis.username=admin
spring.data.redis.password=Modis123@
spring.data.redis.ssl.enabled=false
#JWT
jwt.secret=TDl2RsabrViG+OM6iU++bUkCGG68l88g8AWXekF2Ans=
jwt.expiration=86400000

#RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.rabbitmq.listener.simple.auto-startup=false
spring.rabbitmq.listener.simple.concurrency=3
spring.rabbitmq.listener.simple.max-concurrency=10

rabbitmq.queue.name=modis_notification_queue
rabbitmq.exchange.name=modis_notification_exchange
rabbitmq.routing.key=modis_notification_key

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
