spring.application.name=modis

#MongogoDB Configuration
spring.mongodb.uri=mongodb+srv://22130039_db_user:Thanhdieu@modis.hazw95q.mongodb.net/
spring.mongodb.port=27017
spring.mongodb.database=Modis

#Redis
spring.data.redis.host=redis-16990.c52.us-east-1-4.ec2.cloud.redislabs.com
spring.data.redis.port=16990
spring.data.redis.username=admin
spring.data.redis.password=Modis123@
spring.data.redis.ssl.enabled=false


#JWT
jwt.secret=TDl2RsabrViG+OM6iU++bUkCGG68l88g8AWXekF2Ans=
jwt.expiration=86400000

#RabbitMQ
spring.rabbitmq.listener.simple.auto-startup=false

